[workspace]
authors = ["Hameer Abbasi <2190658+hameerabbasi@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "finch-rs"
platforms = ["osx-arm64", "linux-64"]
version = "0.0.1"

[activation.env]
RUSTFLAGS = "-D warnings"

[tasks]
format = "cargo fmt"
fix = "cargo clippy --fix"
check = "cargo check && cargo clippy"

[dependencies]
rust = ">=1.91.0"
llvmdev = "20.*"
mlir = "20.*"
rust-src = ">=1.91.0"
